# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Beranda"
  url = "#about"
  weight = 10

[[main]]
  name = "Blog"
  url = "#posts"
  weight = 20

# [[main]]
#   name = "Proyek"
#   url = "#projects"
#   weight = 30

[[main]]
  name = "Publikasi"
  url = "#featured"
  weight = 40

[[main]]
  name = "Presentasi"
  url = "#events"
  weight = 45

[[main]]
  name = "Courses"
  url = "/courses"
  weight = 48

[[main]]
  name = "ðŸŽµ"
  url = "#hobby"
  weight = 50

[[main]]
  name = "Kontak"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
   name = "CV"
   url = "#CV"
   weight = 70

[[main]]
  name = "ðŸ”Ž"
  url = "/search"
  weight = 100